# Generated by Django 5.0.4 on 2024-04-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('F', 'Free'), ('B', 'Booked'), ('U', 'Unavailable')], max_length=1)),
            ],
        ),
    ]
